#!/usr/bin/env python3
"""
Parse a Slack export ZIP and generate a handover document.

Usage:
    python tool-slack-handover-parser.py <export.zip> <channel-name> [--days 21]

Output:
    report-slack-handover-<channel>.md
"""

import json
import zipfile
import argparse
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from collections import defaultdict


def load_users(zf: zipfile.ZipFile) -> dict:
    """Return {user_id: display_name}."""
    try:
        with zf.open("users.json") as f:
            users = json.load(f)
        return {
            u["id"]: u.get("profile", {}).get("display_name") or u.get("real_name", u["id"])
            for u in users
        }
    except KeyError:
        return {}


def load_messages(zf: zipfile.ZipFile, channel: str, since: datetime) -> list[dict]:
    """Load all messages from channel since the given datetime."""
    messages = []
    prefix = f"{channel}/"

    day_files = sorted(
        name for name in zf.namelist()
        if name.startswith(prefix) and name.endswith(".json")
    )

    for name in day_files:
        with zf.open(name) as f:
            day_msgs = json.load(f)
        for msg in day_msgs:
            ts = float(msg.get("ts", 0))
            dt = datetime.fromtimestamp(ts, tz=timezone.utc)
            if dt >= since:
                msg["_dt"] = dt
                messages.append(msg)

    return sorted(messages, key=lambda m: m["ts"])


def resolve_text(text: str, users: dict) -> str:
    """Replace <@USERID> with @name."""
    import re
    def replace(m):
        uid = m.group(1)
        return f"@{users.get(uid, uid)}"
    return re.sub(r"<@([A-Z0-9]+)>", replace, text)


def format_message(msg: dict, users: dict) -> str:
    dt = msg["_dt"].strftime("%b %d %H:%M")
    author = users.get(msg.get("user", ""), msg.get("user", "bot"))
    text = resolve_text(msg.get("text", ""), users).strip()
    if not text:
        return ""
    return f"[{dt}] **{author}**: {text}"


def group_by_day(messages: list[dict]) -> dict:
    days = defaultdict(list)
    for msg in messages:
        day = msg["_dt"].strftime("%Y-%m-%d")
        days[day].append(msg)
    return dict(sorted(days.items()))


def extract_threads(messages: list[dict]) -> dict:
    """Return {thread_ts: [reply_msgs]} — replies only (not root)."""
    threads = defaultdict(list)
    for msg in messages:
        thread_ts = msg.get("thread_ts")
        if thread_ts and thread_ts != msg["ts"]:
            threads[thread_ts].append(msg)
    return threads


def build_report(messages: list[dict], users: dict, channel: str, days: int) -> str:
    lines = [
        f"# Slack Handover — #{channel}",
        f"**Period:** last {days} days  |  **Messages:** {len(messages)}  |  "
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    # Participants
    participants = set()
    for msg in messages:
        uid = msg.get("user")
        if uid:
            participants.add(users.get(uid, uid))
    lines += [
        "## Participants",
        ", ".join(sorted(participants)),
        "",
    ]

    # Chronological log grouped by day
    lines.append("## Chronological Log")
    threads = extract_threads(messages)
    thread_ts_seen = set()

    by_day = group_by_day(messages)
    for day, day_msgs in by_day.items():
        dt = datetime.strptime(day, "%Y-%m-%d")
        lines.append(f"\n### {dt.strftime('%A, %B %d')}")

        for msg in day_msgs:
            ts = msg["ts"]
            thread_ts = msg.get("thread_ts")

            # Skip replies (they're printed under their root)
            if thread_ts and thread_ts != ts:
                continue

            line = format_message(msg, users)
            if not line:
                continue
            lines.append(line)

            # Print thread replies inline
            if ts in threads and ts not in thread_ts_seen:
                thread_ts_seen.add(ts)
                for reply in threads[ts]:
                    r_line = format_message(reply, users)
                    if r_line:
                        lines.append(f"  > {r_line}")

    lines += ["", "---", "*Generated by tool-slack-handover-parser.py*"]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Slack export → handover doc")
    parser.add_argument("export_zip", help="Path to Slack export ZIP")
    parser.add_argument("channel", help="Channel name (without #)")
    parser.add_argument("--days", type=int, default=21, help="How many days back (default 21)")
    args = parser.parse_args()

    zip_path = Path(args.export_zip)
    if not zip_path.exists():
        print(f"Error: {zip_path} not found", file=sys.stderr)
        sys.exit(1)

    since = datetime.now(tz=timezone.utc) - timedelta(days=args.days)

    with zipfile.ZipFile(zip_path) as zf:
        # Verify channel exists
        available = sorted(set(
            name.split("/")[0] for name in zf.namelist()
            if "/" in name and not name.startswith("__")
        ))

        if args.channel not in available:
            print(f"Channel '{args.channel}' not found in export.", file=sys.stderr)
            print(f"Available channels: {', '.join(available)}", file=sys.stderr)
            sys.exit(1)

        users = load_users(zf)
        messages = load_messages(zf, args.channel, since)

    if not messages:
        print(f"No messages found in #{args.channel} for the last {args.days} days.")
        sys.exit(0)

    print(f"Found {len(messages)} messages in #{args.channel} (last {args.days} days)")

    report = build_report(messages, users, args.channel, args.days)

    out_path = zip_path.parent / f"report-slack-handover-{args.channel}.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"Saved: {out_path}")


if __name__ == "__main__":
    main()
